# Generated by Django 5.2.4 on 2026-02-14 14:18

import django.db.models.deletion
import uuid
from urllib.parse import urlparse

from django.db import migrations, models


def populate_domain_from_url(apps, schema_editor):
    """Populate domain field from existing publisher URLs."""
    Publisher = apps.get_model("publishers", "Publisher")
    for publisher in Publisher.objects.all():
        if publisher.url:
            parsed = urlparse(publisher.url)
            hostname = parsed.hostname or ""
            if hostname.startswith("www."):
                hostname = hostname[4:]
            publisher.domain = hostname
        else:
            publisher.domain = f"unknown-{publisher.pk}"
        publisher.save(update_fields=["domain"])


def reverse_populate(apps, schema_editor):
    """No-op reverse -- domain data loss is acceptable on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        # Step 1: Add domain field WITHOUT unique constraint or index
        migrations.AddField(
            model_name='publisher',
            name='domain',
            field=models.CharField(default='', max_length=255),
        ),
        # Step 2: Populate domain from existing URLs
        migrations.RunPython(populate_domain_from_url, reverse_populate),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='publisher',
            name='domain',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        # Remaining fields
        migrations.AddField(
            model_name='publisher',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='robots_txt_found',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='robots_txt_url_allowed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='rsl_detected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='rss_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publisher',
            name='sitemap_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tos_permissions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tos_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publisher',
            name='waf_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='waf_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ResolutionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_url', models.URLField()),
                ('canonical_url', models.URLField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waf_result', models.JSONField(blank=True, null=True)),
                ('tos_result', models.JSONField(blank=True, null=True)),
                ('robots_result', models.JSONField(blank=True, null=True)),
                ('sitemap_result', models.JSONField(blank=True, null=True)),
                ('rss_result', models.JSONField(blank=True, null=True)),
                ('rsl_result', models.JSONField(blank=True, null=True)),
                ('metadata_result', models.JSONField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_jobs', to='publishers.publisher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['canonical_url'], name='publishers__canonic_e29e26_idx'), models.Index(fields=['status'], name='publishers__status_fc403c_idx')],
            },
        ),
    ]
