# Generated by Django 5.2.4 on 2026-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_publisher_domain_publisher_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='fetch_strategy',
            field=models.CharField(blank=True, choices=[('', 'Auto (no preference)'), ('curl_cffi', 'curl-cffi'), ('zyte', 'Zyte API')], default='', max_length=20),
        ),
    ]
