# Generated by Django 5.2.4 on 2026-02-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_publisher_fetch_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
