# Generated by Django 5.2.4 on 2026-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_publisher_publisher_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='ai_bot_blocks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionjob',
            name='ai_bot_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
