# Generated by Django 5.2.4 on 2026-02-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0005_ai_bot_blocking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='detected_waf',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='robots_txt_url_allowed',
        ),
    ]
