# Generated by Django 5.2.4 on 2026-02-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0007_articlemetadata_and_article_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='cc_in_index',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='cc_last_crawl',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publisher',
            name='cc_page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='google_news_readiness',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publisher',
            name='has_news_sitemap',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='update_frequency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='publisher',
            name='update_frequency_confidence',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='publisher',
            name='update_frequency_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionjob',
            name='cc_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionjob',
            name='frequency_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionjob',
            name='news_signals_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionjob',
            name='sitemap_analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
