# Generated by Django 5.2.4 on 2026-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_competitive_intelligence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionjob',
            name='canonical_url',
            field=models.URLField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='resolutionjob',
            name='submitted_url',
            field=models.URLField(max_length=2048),
        ),
    ]
