# Generated by Django 5.2.4 on 2025-07-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsDiscoveryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_of_service_url", models.URLField(blank=True, null=True)),
                ("privacy_policy_url", models.URLField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_discovery",
                        to="publishers.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TermsEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permissions", models.JSONField(default=list)),
                ("territorial_exceptions", models.TextField(blank=True, null=True)),
                ("arbitration_clauses", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_evaluation",
                        to="publishers.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
